user:
  firstName: Abirami devi
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include:
        - "*"
